name: Example User
gender: Male
age: 21
state: Maharashtra
location: Rural
category: Scheduled Caste (SC)
disability: false
minority: true
student: true
bpl: false
family_income: 250000
parent_income: 300000